// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEs2aghhtcIIuxKSoRxiCRPGZsffPKDpI',
    appId: '1:666180816996:web:dad0df4c76a26da67bcf71',
    messagingSenderId: '666180816996',
    projectId: 'todo-app-30980',
    authDomain: 'todo-app-30980.firebaseapp.com',
    storageBucket: 'todo-app-30980.appspot.com',
    measurementId: 'G-K3PY305Z0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBefHm5Mx9BlU5P5VGv_P-aXP6VSBEdpg',
    appId: '1:666180816996:android:87c66aa87fc382a27bcf71',
    messagingSenderId: '666180816996',
    projectId: 'todo-app-30980',
    storageBucket: 'todo-app-30980.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEIxl2z6ycX0gnk3QM_Zia82oQFWASpgk',
    appId: '1:666180816996:ios:9eed9b5f57b05c287bcf71',
    messagingSenderId: '666180816996',
    projectId: 'todo-app-30980',
    storageBucket: 'todo-app-30980.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEIxl2z6ycX0gnk3QM_Zia82oQFWASpgk',
    appId: '1:666180816996:ios:3be87d4ea2eff36e7bcf71',
    messagingSenderId: '666180816996',
    projectId: 'todo-app-30980',
    storageBucket: 'todo-app-30980.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
